### ISSUE TITLE
enhance zipwrapper plugin to decompress whole tar/zip archives

### ISSUE THREAD

**Issue by aowen87** [LLNL/Silo#102]
This was requested a user in the wild

-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. As such, not all 
information was able to be captured in the transition. Below is
a complete record of the original redmine ticket.

Ticket number: 782
Status: Pending
Project: VisIt
Tracker: Feature
Priority: Normal
Subject: enhance zipwrapper plugin to decompress whole tar/zip archives
Assigned to: -
Category: -
Target version: -
Author: Mark Miller
Start: 07/11/2011
Due date: 
% Done: 0%
Estimated time: 
Created: 07/11/2011 05:28 pm
Updated: 08/05/2011 07:38 pm
Likelihood: 
Severity: 
Found in version: 2.12.3
Impact: 2 - Low
Expected Use: 3 - Occasional
OS: All
Support Group: Any
Description:
 This was requested a user in the wild

Comments:
Actually I think the request was from an LLNL user. Request was from me (Tanim Islam). It would be "nice" in terms of output data representation, to have a collection of silo files stored in an archive.

**Comment by markcmiller86** [comment]
Already in progress in VisIt project
