### ISSUE TITLE
fix dir creation performance issues

### ISSUE THREAD

**Issue by aowen87** [LLNL/Silo#167]
surface86{miller86}233: ./dir ndirs=10000 time to create 10000 dirs = 0.746675 seconds surface86{miller86}234: ./dir ndirs=100000 time to create 100000 dirs = 90.5541 seconds surface86{miller86}235: ./dir ndirs=10000 DB_HDF5 time to create 10000 dirs = 13.6996 seconds surface86{miller86}236: ./dir ndirs=100000 DB_HDF5 time to create 100000 dirs = 2688.48 seconds

-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. As such, not all 
information was able to be captured in the transition. Below is
a complete record of the original redmine ticket.

Ticket number: 2464
Status: Pending
Project: VisIt
Tracker: Bug
Priority: Normal
Subject: fix dir creation performance issues
Assigned to: Mark Miller
Category: -
Target version: 4.11.0
Author: Mark Miller
Start: 12/02/2015
Due date: 
% Done: 0%
Estimated time: 
Created: 12/02/2015 02:01 pm
Updated: 12/08/2016 11:31 pm
Likelihood: 3 - Occasional
Severity: 2 - Minor Irritation
Found in version: 4.8
Impact: 
Expected Use: 
OS: All
Support Group: Any
Description:
 surface86{miller86}233: ./dir ndirs=10000 time to create 10000 dirs = 0.746675 seconds surface86{miller86}234: ./dir ndirs=100000 time to create 100000 dirs = 90.5541 seconds surface86{miller86}235: ./dir ndirs=10000 DB_HDF5 time to create 10000 dirs = 13.6996 seconds surface86{miller86}236: ./dir ndirs=100000 DB_HDF5 time to create 100000 dirs = 2688.48 seconds

Comments:

**Comment by markcmiller86** [comment]
This too is unreproducible
