### ISSUE TITLE
fix leak of udata in FIC vfd

### ISSUE THREAD

**Issue by aowen87** [LLNL/Silo#172]
udata_free is being called but reference counts are such that it doesn't get freed

-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. As such, not all 
information was able to be captured in the transition. Below is
a complete record of the original redmine ticket.

Ticket number: 2621
Status: New
Project: VisIt
Tracker: Bug
Priority: Normal
Subject: fix leak of udata in FIC vfd
Assigned to: -
Category: -
Target version: -
Author: Mark Miller
Start: 05/27/2016
Due date: 
% Done: 0%
Estimated time: 
Created: 05/27/2016 01:32 am
Updated: 
Likelihood: 3 - Occasional
Severity: 2 - Minor Irritation
Found in version: 4.8
Impact: 
Expected Use: 
OS: All
Support Group: Any
Description:
 udata_free is being called but reference counts are such that it doesn't get freed

Comments:

**Comment by markcmiller86** [comment]
duplicates #183
