### ISSUE TITLE
Stand up HDF5's own testing on LLNL systems

### ISSUE THREAD

**Issue by aowen87** [LLNL/Silo#194]
HDF5 has its own, regular testing suite. We'd like to stand up that test suite on dawndev and one of LLNL's Linux clusters.

-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. As such, not all 
information was able to be captured in the transition. Below is
a complete record of the original redmine ticket.

Ticket number: 596
Status: New
Project: VisIt
Tracker: Feature
Priority: Normal
Subject: Stand up HDF5's own testing on LLNL systems
Assigned to: -
Category: -
Target version: -
Author: Mark Miller
Start: 02/10/2011
Due date: 02/28/2011
% Done: 0%
Estimated time: 32.00 hours
Created: 02/10/2011 12:30 am
Updated: 
Likelihood: 
Severity: 
Found in version: 
Impact: 3 - Medium
Expected Use: 3 - Occasional
OS: All
Support Group: Any
Description:
 HDF5 has its own, regular testing suite. We'd like to stand up that test suite on dawndev and one of LLNL's Linux clusters.

Comments:

**Comment by markcmiller86** [comment]
This has basically been done. THG tracks status on their [CDash site](https://cdash.hdfgroup.org/index.php?project=HDF5)
