### ISSUE TITLE
Deleting the 4.11 branch

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/Silo#231]
I am recording here some notes about this so we have a record.

We have two branches, `4.11` and `4.11RC`. To can't recall now why I wound up creating these two similarly named and purposed branches but we've done most of our work on the branch named `4.11RC`. There are only 4 commits on the `4.11` branch and I believe all the work there was actually also merged to `main`. However, in the picture below (from `tkcvs`), I see no merge arrows *from* `4.11` to anything.

I have been using `gitk` and `tkcvs` to browse around the Git repo (locally). Attached is a screen shot from `tkcvs` showing some of the branches...

![Screen Shot 2021-12-02 at 5 36 04 PM](https://user-images.githubusercontent.com/5720676/144929345-e1386da8-a71a-41d5-81de-c8173e4d52df.png)

You will see branch with `HEAD` named `origin/4.11` and that branch I am planning on deleting. 

@biagas...do you see any problems with my so doing?

**Comment by biagas** [comment]
No problems that I can see.

**Comment by markcmiller86** [comment]
This has been done.
