### ISSUE TITLE
tests/matf77.f is actually broken under Gentoo Linux

### ISSUE THREAD

**Issue by scardracs** [LLNL/Silo#234]
Hi everyone,

I'm actually porting silo to 4.11 on gentoo but we need to have a working testsuite, if present.
I'm facing problems with matf77.f, as shown below:

matf77.f:250:43:

```
  244 |      .                  meshnms, lmeshnms, meshtypes,
      |                                           2
......
  250 |      .                  meshnms, lmeshnms, DB_F77NULL,
      |                                           1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
make[1]: *** [Makefile:1987: matf77.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/portage/sci-libs/silo-4.11/work/silo-4.11-bsd/tests'
make: *** [Makefile:2114: check-am] Error 2
make: Leaving directory '/var/tmp/portage/sci-libs/silo-4.11/work/silo-4.11-bsd/tests'
```

Any ideas on how to fix it?

**Comment by scardracs** [comment]
I've made a PR for it [here](https://github.com/gentoo/gentoo/pull/23306), taking up required patches on [debian](https://sources.debian.org/patches/silo-llnl/4.11-2/)

**Comment by markcmiller86** [comment]
Am reproducing now and working on fix. That said, this feels a bit like a potential compiler bug.

It is complaining about the fact that in one call to `dbputmmesh()` on line `244` an integer array of length 3 is being passed (e.g. rank-1) and in the other call on line `250` a constant/scalar is being passed for the same argument.

The argument is passed by reference in either case. So, in either case, the called function is seeing an array of integers. In the first case, it is an array with 3 entries. In the second case, it is an array with a single, scalar entry, the scalar `DB_F77NULL`. Am I missing something?

I can reproduce the same problem by doing something like defining local integer array `foo` and then passing that array for the 3rd argument in the second call.

```
.
.
.
      integer  dims(2), err, optlist, lmeshnms(3)
      integer  meshtypes(3)
      integer  foo(3)
.
.
.
      err = dbputmmesh (dbid, "multimesh", 9, 3,
     .                  meshnms, lmeshnms, meshtypes,
     .                  DB_F77NULL, id)
      btype = DB_UCDMESH
      err = dbmkoptlist (5, ol)
      err = dbaddiopt   (ol, DBOPT_MB_BLOCK_TYPE, btype)  ! integer
      foo(1) = 10
      err = dbputmmesh (dbid, "multimesh2", foo, 3,
     .                  meshnms, lmeshnms, meshtypes,
     .                  ol, id)
```

**Comment by markcmiller86** [comment]
Also, in doing a bit of research, it looks like many others are stumbling into similar issue with gcc-10...

* [spack](https://github.com/spack/spack/search?q=%22rank+mismatch%22&type=issues)
* [scipy](https://github.com/scipy/scipy/issues/11611) (agree with comments there...this seems like a gcc bug)

and a quick fix is to add `-fallow-argument-mismatch` to `CFLAGS`

**Comment by markcmiller86** [comment]
Ok, I don't see a better way to fix this. IMHO, gcc 10 got a little heavy handed with declaring this a compilation failure instead of warning.

For better or worse, F77 code has allowed this kind of coding construct for close to 50 years and a compiler deciding now its a fatal error is a little ridiculous. Your best option is to add the `-fallow-argument-mismatch` to `FFLAGS`. Another option is to compile with `-std=legacy`.

Either would be needed *only* to compile a source file in which you happen to be using the interface the two different ways that are supported. Otherwise, the flag is not needed.

**Comment by scardracs** [comment]
Actually I'm using gcc-11.2.1 on Gentoo, I'll try using the CFLAGS suggested during test time and see if it works

**Comment by scardracs** [comment]
I confirm that using -fallow-argument-mismatch actually did the trick, thanks :)
