### ISSUE TITLE
Invalid code for python check in configure / configure.ac 

### ISSUE THREAD

**Issue by StefanBruens** [LLNL/Silo#271]
https://github.com/LLNL/Silo/blob/2597088f1b0c48873fee8635ce788df0defaf5b2/configure.ac#L1138

The `print ...` statement should be `print(...)`. This is also compatible with Python 2 (at least 2.7), and any 3.x version.

**Comment by markcmiller86** [comment]
yeah, just saw this and patched it in a local build. Don't know how long we'll continue supporting autotools builds though.
