### ISSUE TITLE
Missing reference to Github repository on Silo homepage

### ISSUE THREAD

**Issue by StefanBruens** [LLNL/Silo#272]
https://wci.llnl.gov/simulation/computer-codes/silo

There is no reference to the Github repository on the homepage.

**Comment by StefanBruens** [comment]
(There is one reference on the "Documentation" tab below under "Useful links", but at least I missed that one).

**Comment by markcmiller86** [comment]
Corrected now [here](https://software.llnl.gov/Silo/more/)
