### ISSUE TITLE
Adapt to `H5FD_class_t` change in HDF5 1.13

### ISSUE THREAD

**Issue by eschnett** [LLNL/Silo#304]
The layout of `H5FD_class_t` changed in HDF5 1.14. There are four new fields that need to be initialized (`{read|write}_{vector|selection}`). This looks similar to https://github.com/LLNL/Silo/pull/260.

**Comment by eschnett** [comment]
If the layout of `H5FD_class_t` keeps changing in the HDF5 library, then you could do either of these two approaches to either detect or try to avoid future trouble:

1. Calculate the expected size of the struct, and `static_assert` that this is indeed true.
2. When initializing the struct, use `memset` and `sizeof` to initialize it to all zero (that's probably correct on all supported architectures), and then explicitly set some of the fields.

**Comment by markcmiller86** [comment]
- Original work went on `main` in 5dc160c7ae489b8181874dccf7ce3b8089c128f5
- Backported to `4.11RC` in 5b67ad096399a5fd5b92312910cf234e38907fe2
