### ISSUE TITLE
Issue with hdf5_dvr DB_OJB_CASE macro

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/Silo#309]
I was trying to build this and ran into an issue with the `DB_OBJ_CASE` macro trying to strdup a char. I have a patch to fix this that changes `DBcurve_mt::yvarname` from a `char[256]` to a `char[1][256]` but I feel like that is maybe not the best solution.

https://github.com/LLNL/Silo/blob/main/src/hdf5_drv/silo_hdf5.c#L1869

@markcmiller86

**Comment by kwryankrattiger** [comment]
Build info:
* OLCF Frontier
* CCE 15.0.0
* Spack install
* Silo@4.11
* HDF5 1.14.0

**Comment by markcmiller86** [comment]
Fixed on 4.11RC here, https://github.com/LLNL/Silo/commit/be29ddf0352bc8e5a7eecc8772a3acb64dfde18c and on which needs to get merged to `main` also.
