### ISSUE TITLE
Failure of db_hdf5_MkDir

### ISSUE THREAD

**Issue by nDimensionalSpace** [LLNL/Silo#339]
db_hdf5_MkDir returns the error text "Low-level function call failed".  This occurs on both rzwhippet and rztopaz (toss_4), but not on rzgenie (toss_3) (to the extent that I can determine).  Occurrences seem stochastic and non-repeatable, but I have seen the error occur between 1 and 6 hours into a run, and in particular, not on the first plot state.  Screenshot attached.

![Screen Shot 2023-08-02 at 7 44 49 AM](https://github.com/LLNL/Silo/assets/34101746/f55061c8-ea4e-42be-b37b-6172892885e3)

**Comment by markcmiller86** [comment]
Are you using the toss4 builds on the rz for the cases that are failing?

**Comment by nDimensionalSpace** [comment]
No, we aren't . . .  On toss3, for some reason, we were doing our own build.  Maybe you made some changes for us that weren't publicly available, I can't recall.

**Comment by markcmiller86** [comment]
Ok, does that mean you are using toss3 builds on the toss4 systems though?

If so, I worry that using a toss3 build on a toss4 system, some behavior may be indeterminiate.

There are toss4 builds available there on rz for Silo 4.11.0 I think.

**Comment by nDimensionalSpace** [comment]
Ah right.  No, we rebuilt all of our libs for toss4.  I am looking at the settings file right now, and it has the requisite references to toss4 throughout.  I was just wondering about whether you all did any kind of build tuning associated with changes in the fs . . .

**Comment by markcmiller86** [comment]
> I was just wondering about whether you all did any kind of build tuning associated with changes in the fs . . .

In the jump from 4.10.3 to 4.11, a lot changed and yes, I think some performance issues were tuned. That said, none of it was file system specific. Are all of your runs on Lustre or some on Lustre and some on IBM Spectrum Scale (GPFS)?

**Comment by nDimensionalSpace** [comment]
The ones that are erroring out are all on lustre.

**Comment by markcmiller86** [comment]
@nDimensionalSpace apologies but what version of Silo?I should adjust Silo's error messages to include that.

**Comment by nDimensionalSpace** [comment]
4.10.2

**Comment by nDimensionalSpace** [comment]
@markcmiller86: Any further thoughts on this, or is "try the system builds" the primary tactic at this point?  Thx

**Comment by markcmiller86** [comment]
Sorry...very puzzling. I was expecting you were going to tell me you are seeing on 4.11, not 4.10.2 (or 4.10.3). That said, I guess I am still not clear on one point...did you build 4.10.2 for toss4? If so, did you also build HDF5 for toss4?

**Comment by nDimensionalSpace** [comment]
Yes, we built HDF5 for toss4, and used that as the dependency for Silo 4.10.2 to be built on toss4 as well.

**Comment by markcmiller86** [comment]
> Yes, we built HDF5 for toss4, and used that as the dependency for Silo 4.10.2 to be built on toss4 as well.

Ok, am slammed with meetings today. Expect to take a look tomorrow PM. I am not sure I'll be able to reproduce without more info.

**Comment by nDimensionalSpace** [comment]
Grrr . . .  I just spent the last two days running all possible permutations of the effected problem, and no luck.  😐

I am going to close this issue now.  But if it comes up again and I recall this discussion, I will reopen this guy, and pass you the files.

**Comment by markcmiller86** [comment]
I wonder if it was intermittent file system behavior. That is not unheard of. Thanks for taking the time to reproduce. If you have a moment and can outline here in words the basic paradigm you think was triggering it, I might be able to think through a possible reproducer.

**Comment by nDimensionalSpace** [comment]
@markcmiller86: Hmmm . . .  Ok, everything I imagine about this:

(1) The version of silo I was using is based on our HDF build, which afair, has a few special build flags to improve performance.
(2) The problem I was running was for debugging, so I was writing out Silo states every time step.  But the time steps were pretty fast, so if there was lag in the file system, maybe the previous plot state was not closing fast enough.
(3) It is also the case that certain processes had no or almost no mesh on them, while some processes were not huge, but large enough.  So, same thing: if the previous process was not done writing a file before the next process started trying to do stuff, maybe that was causing issues.
(4) Maybe (2) and (3) were combining in some especially pernicious way.

All of those things seem vaguely like grasping at straws, but that is all I have.
