### ISSUE TITLE
Silo 4.10.2-bsd download link stopped working

### ISSUE THREAD

**Issue by G-071** [LLNL/Silo#351]
The download link for the Silo 4.10.2-bsd
( https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.10.2-bsd.tgz ) recently stopped working which broke our CI pipelines in  [Octo-Tiger](https://github.com/STEllAR-GROUP/octotiger) as we use it as a dependency.

Notably, this download link is also still used for the 4.10.2-bsd version in the [Silo Spack package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/silo/package.py), so I would not be surprised if this broke a few other builds.

Is the download link for this version being moved permanently? In that case, the Spack recipe should be modified accordingly.

**Comment by markcmiller86** [comment]
I have finally corrected this by starting a new [web site](https://silo.llnl.gov). You can find [new and older releases](https://software.llnl.gov/Silo/ghpages/releases/releases.html) there.

**Comment by markcmiller86** [comment]
closing
