### ISSUE TITLE
Building on crossroads platform fails with the message "call to undeclared function"

### ISSUE THREAD

**Issue by nDimensionalSpace** [LLNL/Silo#370]
Not sure what the preferred way of dealing with this is . . .  Attached screenshot captures error.

![Screenshot 2024-03-14 at 12 00 49 PM](https://github.com/LLNL/Silo/assets/34101746/7ec5e4f4-00ec-4ed6-997a-f15b8325bc58)

**Comment by markcmiller86** [comment]
Hmm....This is for a build of HDF5? What version and what was the config or cmake command? It looks like two things are going on. For some reason, Its using flags `icx` doesn't like. Hmm...what is `icx`? Intel C++ compiler? Are you building hdf5's C++ interface? The other issue is the outright error, `H5D__layout_set_version` and that seems like a missing header or something. Is this on Windows?

**Comment by markcmiller86** [comment]
@nDimensionalSpace also, screen shots are helpful but not as helpful as searchable text if you can swing it.

**Comment by markcmiller86** [comment]
Oh, I see headline so this is on crossroads, eh? I did build HDF5 on crossroads earlier this week for VisIt but its a very old 1.8 version I think. You might be able to find it `/usr/projects/views/visit/3.4.0/<arch>/lib`

**Comment by nDimensionalSpace** [comment]
Ugh . . .  My current degree of parallelism is messing with me.  I will get back when Silo is the one holding me up.

Sorry, Mark.
