### ISSUE TITLE
Can silo compile to shared libraries?

### ISSUE THREAD

**Issue by VictorEijkhout** [LLNL/Silo#401]
I'm using 4.11.1 and my lib directory contains:
```
libsilo.a  libsiloh5.a  libsiloh5.la*  libsiloh5.settings*  libsilo.la*  libsilo.settings*
```
Is there a way to get `.so` shared libraries?

**Comment by markcmiller86** [comment]
Shared libraries should be the default. But, you can try add `--enable-shared` to the configure command.
